# the error that means that it was not possible to create a review about the user
REVIEW_CREATE_ERROR: dict[str, str] = {"error": "cant_leave_review_about_yourself"}
